# ~/.config/walker/config.toml
force_keyboard_focus = true
selection_wrap = true
theme = "grott"
hide_action_hints = true

[style]
border_radius = 18
padding = 24
anchor = "center"

[keybinds]
accept   = ["Return"]
abort    = ["Escape", "Ctrl+c"]
next     = ["Down", "j"]
previous = ["Up", "k"]

[placeholders]
default = { input = " Search", list = "" }

